export const defaultState: AppState = {
  appIsInited: false,
  isLoading: false,
  view: null,
  signInFormError: null,
  signUpFormError: null,
  profileEditFormError: null,
  passwordChangeFormError: null,
  addUserError: null,
  removeUserError: null,
  user: null,
  chats: [],
  messages: [],
  chatUsers: [],
  searchResults: [],
  socket: null,
};
